// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_find_balanced_subset
LogicalVector cpp_find_balanced_subset(IntegerVector gen, IntegerVector env, int n_gen_levels, int n_env_levels);
RcppExport SEXP _MERIDIAN_cpp_find_balanced_subset(SEXP genSEXP, SEXP envSEXP, SEXP n_gen_levelsSEXP, SEXP n_env_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type gen(genSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type env(envSEXP);
    Rcpp::traits::input_parameter< int >::type n_gen_levels(n_gen_levelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_env_levels(n_env_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_balanced_subset(gen, env, n_gen_levels, n_env_levels));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ge_means
NumericMatrix cpp_ge_means(IntegerVector gen, IntegerVector env, NumericVector trait, int n_gen, int n_env);
RcppExport SEXP _MERIDIAN_cpp_ge_means(SEXP genSEXP, SEXP envSEXP, SEXP traitSEXP, SEXP n_genSEXP, SEXP n_envSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type gen(genSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type env(envSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trait(traitSEXP);
    Rcpp::traits::input_parameter< int >::type n_gen(n_genSEXP);
    Rcpp::traits::input_parameter< int >::type n_env(n_envSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ge_means(gen, env, trait, n_gen, n_env));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ammi_stability
DataFrame cpp_ammi_stability(NumericMatrix gen_ipca_scores, NumericVector axis_ss, NumericVector axis_pct, int n_axis);
RcppExport SEXP _MERIDIAN_cpp_ammi_stability(SEXP gen_ipca_scoresSEXP, SEXP axis_ssSEXP, SEXP axis_pctSEXP, SEXP n_axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type gen_ipca_scores(gen_ipca_scoresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type axis_ss(axis_ssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type axis_pct(axis_pctSEXP);
    Rcpp::traits::input_parameter< int >::type n_axis(n_axisSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ammi_stability(gen_ipca_scores, axis_ss, axis_pct, n_axis));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fw_regression
DataFrame cpp_fw_regression(NumericVector mean_vals, NumericVector ei_vals, IntegerVector gen_ids, int n_gen);
RcppExport SEXP _MERIDIAN_cpp_fw_regression(SEXP mean_valsSEXP, SEXP ei_valsSEXP, SEXP gen_idsSEXP, SEXP n_genSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mean_vals(mean_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ei_vals(ei_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gen_ids(gen_idsSEXP);
    Rcpp::traits::input_parameter< int >::type n_gen(n_genSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fw_regression(mean_vals, ei_vals, gen_ids, n_gen));
    return rcpp_result_gen;
END_RCPP
}
// cpp_impute_additive_gxe
List cpp_impute_additive_gxe(NumericMatrix ge_means);
RcppExport SEXP _MERIDIAN_cpp_impute_additive_gxe(SEXP ge_meansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ge_means(ge_meansSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_impute_additive_gxe(ge_means));
    return rcpp_result_gen;
END_RCPP
}
// cpp_er_statistics
DataFrame cpp_er_statistics(NumericMatrix ge_means, NumericVector env_index);
RcppExport SEXP _MERIDIAN_cpp_er_statistics(SEXP ge_meansSEXP, SEXP env_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ge_means(ge_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type env_index(env_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_er_statistics(ge_means, env_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_group_numeric_summary
DataFrame cpp_group_numeric_summary(IntegerVector group, NumericVector value, int n_group);
RcppExport SEXP _MERIDIAN_cpp_group_numeric_summary(SEXP groupSEXP, SEXP valueSEXP, SEXP n_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< int >::type n_group(n_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_group_numeric_summary(group, value, n_group));
    return rcpp_result_gen;
END_RCPP
}
// cpp_detect_outliers
LogicalVector cpp_detect_outliers(IntegerVector group, NumericVector value, int n_group, std::string method, double threshold);
RcppExport SEXP _MERIDIAN_cpp_detect_outliers(SEXP groupSEXP, SEXP valueSEXP, SEXP n_groupSEXP, SEXP methodSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< int >::type n_group(n_groupSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_detect_outliers(group, value, n_group, method, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_spatial_cell_summary
DataFrame cpp_spatial_cell_summary(IntegerVector cell_id, NumericVector column, NumericVector row, NumericVector raw, NumericVector fitted, NumericVector residual, NumericVector genotype, NumericVector weight, int n_cell);
RcppExport SEXP _MERIDIAN_cpp_spatial_cell_summary(SEXP cell_idSEXP, SEXP columnSEXP, SEXP rowSEXP, SEXP rawSEXP, SEXP fittedSEXP, SEXP residualSEXP, SEXP genotypeSEXP, SEXP weightSEXP, SEXP n_cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cell_id(cell_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type column(columnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type row(rowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type raw(rawSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fitted(fittedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type residual(residualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type genotype(genotypeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type n_cell(n_cellSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_spatial_cell_summary(cell_id, column, row, raw, fitted, residual, genotype, weight, n_cell));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MERIDIAN_cpp_find_balanced_subset", (DL_FUNC) &_MERIDIAN_cpp_find_balanced_subset, 4},
    {"_MERIDIAN_cpp_ge_means", (DL_FUNC) &_MERIDIAN_cpp_ge_means, 5},
    {"_MERIDIAN_cpp_ammi_stability", (DL_FUNC) &_MERIDIAN_cpp_ammi_stability, 4},
    {"_MERIDIAN_cpp_fw_regression", (DL_FUNC) &_MERIDIAN_cpp_fw_regression, 4},
    {"_MERIDIAN_cpp_impute_additive_gxe", (DL_FUNC) &_MERIDIAN_cpp_impute_additive_gxe, 1},
    {"_MERIDIAN_cpp_er_statistics", (DL_FUNC) &_MERIDIAN_cpp_er_statistics, 2},
    {"_MERIDIAN_cpp_group_numeric_summary", (DL_FUNC) &_MERIDIAN_cpp_group_numeric_summary, 3},
    {"_MERIDIAN_cpp_detect_outliers", (DL_FUNC) &_MERIDIAN_cpp_detect_outliers, 5},
    {"_MERIDIAN_cpp_spatial_cell_summary", (DL_FUNC) &_MERIDIAN_cpp_spatial_cell_summary, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_MERIDIAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
