# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_find_balanced_subset <- function(gen, env, n_gen_levels, n_env_levels) {
    .Call(`_MERIDIAN_cpp_find_balanced_subset`, gen, env, n_gen_levels, n_env_levels)
}

cpp_ge_means <- function(gen, env, trait, n_gen, n_env) {
    .Call(`_MERIDIAN_cpp_ge_means`, gen, env, trait, n_gen, n_env)
}

cpp_ammi_stability <- function(gen_ipca_scores, axis_ss, axis_pct, n_axis) {
    .Call(`_MERIDIAN_cpp_ammi_stability`, gen_ipca_scores, axis_ss, axis_pct, n_axis)
}

cpp_fw_regression <- function(mean_vals, ei_vals, gen_ids, n_gen) {
    .Call(`_MERIDIAN_cpp_fw_regression`, mean_vals, ei_vals, gen_ids, n_gen)
}

cpp_impute_additive_gxe <- function(ge_means) {
    .Call(`_MERIDIAN_cpp_impute_additive_gxe`, ge_means)
}

cpp_er_statistics <- function(ge_means, env_index) {
    .Call(`_MERIDIAN_cpp_er_statistics`, ge_means, env_index)
}

cpp_group_numeric_summary <- function(group, value, n_group) {
    .Call(`_MERIDIAN_cpp_group_numeric_summary`, group, value, n_group)
}

cpp_detect_outliers <- function(group, value, n_group, method, threshold) {
    .Call(`_MERIDIAN_cpp_detect_outliers`, group, value, n_group, method, threshold)
}

cpp_spatial_cell_summary <- function(cell_id, column, row, raw, fitted, residual, genotype, weight, n_cell) {
    .Call(`_MERIDIAN_cpp_spatial_cell_summary`, cell_id, column, row, raw, fitted, residual, genotype, weight, n_cell)
}

